image: node

stages:
  - lint
  - build
  - release

cache:
  paths:
    - node_modules/

lint:
  stage: lint
  rules:
    - if: "$CI_COMMIT_BRANCH"
    - if: "$CI_COMMIT_TAG"
      when: never
  script:
    - npm i
    - npx eslint .
    - npx prettier --check .

build:
  stage: build
  before_script:
    - "command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - echo "$PF1_DEPLOY_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - gitlab_hostname=$(echo "${CI_REPOSITORY_URL}" | sed -e 's|https\?://gitlab-ci-token:.*@||g' | sed -e 's|/.*||g')
    - ssh-keyscan "${gitlab_hostname}" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - apt-get update
    - apt-get install zip
    - npm i
    - npm run build
    - mv dist pf1
    - zip -q pf1.zip -r pf1
    - node getChangelog.js
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file pf1.zip ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/pf1release/${CI_COMMIT_TAG}/pf1.zip
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file system.json ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/pf1release/${CI_COMMIT_TAG}/system.json
    - url_host=$(echo "${CI_REPOSITORY_URL}" | sed -e 's|https\?://gitlab-ci-token:.*@|ssh://git@|g')
    - git remote set-url origin "${url_host}"
    - git config user.name $GITLAB_USER_LOGIN
    - git config user.email $GITLAB_USER_EMAIL
    - git tag -f latest
    - git push origin latest -f
  artifacts:
    paths:
      - pf1.zip
      - system.json
      - recent-changes.md
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG !~ "latest"'

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG !~ "latest"'
  script:
    - |
      release-cli create --name "Release $CI_COMMIT_TAG" --description "$(cat recent-changes.md)" --tag-name $CI_COMMIT_TAG \
                                                                                   --assets-link "{\"name\":\"pf1.zip\",\"url\":\"${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/pf1release/${CI_COMMIT_TAG}/pf1.zip\"}" \
                                                                                   --assets-link "{\"name\":\"system.json\",\"url\":\"${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/pf1release/${CI_COMMIT_TAG}/system.json\"}"
